# This is a basic workflow to help you get started with Actions

name: Songs.json Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
    paths:
      - "songs.json"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run PianoController.jar
        run: java -jar PianoController.jar songdb-verification --github-action

      - name: Commit and push changes
        run: |
          git config --local user.name SongDB-Checker
          git config --local user.email "actions@github.com" 
          if ! git diff --exit-code; then
              git add *
              git commit -am "GH Action - Auto-Update songs.json" 
              git push -f origin main
          fi
